// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Proyecto.Datos.Contexto.Repositorio;

namespace Proyecto.Datos.Contexto
{
    public partial class ContextoProyecto : DbContext
    {
        public ContextoProyecto()
        {
        }

        public ContextoProyecto(DbContextOptions<ContextoProyecto> options)
            : base(options)
        {
        }

        public virtual DbSet<Hijos> Hijos { get; set; }
        public virtual DbSet<Padres> Padres { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Hijos>(entity =>
            {
                entity.HasKey(e => e.Identificacion)
                    .HasName("PK__Hijos__D6F931E4C5EBD324");

                entity.Property(e => e.Identificacion).ValueGeneratedNever();

                entity.Property(e => e.Apellidos)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.DescripcionFisica)
                    .HasMaxLength(500)
                    .IsUnicode(false);

                entity.Property(e => e.Estudia)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false);

                entity.Property(e => e.FechaNacimiento).HasColumnType("datetime");

                entity.Property(e => e.Genero)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false);

                entity.Property(e => e.Nombres)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.HasOne(d => d.IdentificacionMadreNavigation)
                    .WithMany(p => p.HijosIdentificacionMadreNavigation)
                    .HasForeignKey(d => d.IdentificacionMadre)
                    .HasConstraintName("FK__Hijos__Identific__276EDEB3");

                entity.HasOne(d => d.IdentificacionPadreNavigation)
                    .WithMany(p => p.HijosIdentificacionPadreNavigation)
                    .HasForeignKey(d => d.IdentificacionPadre)
                    .HasConstraintName("FK__Hijos__Identific__267ABA7A");
            });

            modelBuilder.Entity<Padres>(entity =>
            {
                entity.HasKey(e => e.Identificacion)
                    .HasName("PK__Padres__D6F931E42923EE88");

                entity.Property(e => e.Identificacion).ValueGeneratedNever();

                entity.Property(e => e.Apellidos)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.FechaNacimiento).HasColumnType("datetime");

                entity.Property(e => e.Genero)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false);

                entity.Property(e => e.Nombres)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Observaciones)
                    .HasMaxLength(500)
                    .IsUnicode(false);

                entity.Property(e => e.TipoEmpleo)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}