//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.IC.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rcsUtilitarios {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rcsUtilitarios() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Proyecto.IC.Recursos.rcsUtilitarios", typeof(rcsUtilitarios).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Año(s) .
        /// </summary>
        public static string Anios {
            get {
                return ResourceManager.GetString("Anios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CadenaConexion.
        /// </summary>
        public static string CadenaConexion {
            get {
                return ResourceManager.GetString("CadenaConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CadenaConexionADO.
        /// </summary>
        public static string CadenaConexionADO {
            get {
                return ResourceManager.GetString("CadenaConexionADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CadenaConexionLDAP.
        /// </summary>
        public static string CadenaConexionLDAP {
            get {
                return ResourceManager.GetString("CadenaConexionLDAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen caracteres no válidos.
        /// </summary>
        public static string CaracteresIncorrectos {
            get {
                return ResourceManager.GetString("CaracteresIncorrectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cierre Anual.
        /// </summary>
        public static string CierreAnual {
            get {
                return ResourceManager.GetString("CierreAnual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO-8859-8.
        /// </summary>
        public static string Codificacion_ISO_8859_8 {
            get {
                return ResourceManager.GetString("Codificacion-ISO-8859-8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Día(s).
        /// </summary>
        public static string Dias {
            get {
                return ResourceManager.GetString("Dias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La solicitud {0} {1} fallo con estado {2} con los parametros {3} y el contenido {4}.
        /// </summary>
        public static string ErrorConsumoServicioRest {
            get {
                return ResourceManager.GetString("ErrorConsumoServicioRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha generado un inconveniente al realizar la operacion por favor comunicarse a mesa de ayuda y/o soporte a los telefonos 345678 con el ticket {0}.
        /// </summary>
        public static string ErrorExcepcionNoControlada {
            get {
                return ResourceManager.GetString("ErrorExcepcionNoControlada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rango de fechas no valido..
        /// </summary>
        public static string ErrorRangoFecha {
            get {
                return ResourceManager.GetString("ErrorRangoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al serializar:.
        /// </summary>
        public static string ErrorSerializar {
            get {
                return ResourceManager.GetString("ErrorSerializar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesion no valida , ingrese nuevamente por favor..
        /// </summary>
        public static string ErrorSesionNoValida {
            get {
                return ResourceManager.GetString("ErrorSesionNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token de autorización invalido..
        /// </summary>
        public static string ErrorTokenNoValido {
            get {
                return ResourceManager.GetString("ErrorTokenNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token de autorización es obligatorio..
        /// </summary>
        public static string ErrorTokenObligatorio {
            get {
                return ResourceManager.GetString("ErrorTokenObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tiene permisos para realizar esta acción..
        /// </summary>
        public static string ErrorUsuarioNoAutorizado {
            get {
                return ResourceManager.GetString("ErrorUsuarioNoAutorizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error validando el permiso..
        /// </summary>
        public static string ErrorValidandoPermiso {
            get {
                return ResourceManager.GetString("ErrorValidandoPermiso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error validando el token..
        /// </summary>
        public static string ErrorValidandoToken {
            get {
                return ResourceManager.GetString("ErrorValidandoToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El formato del correo electrónico no es válido.
        /// </summary>
        public static string FormatoInvalidoCorreoElectronico {
            get {
                return ResourceManager.GetString("FormatoInvalidoCorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La url no es válida.
        /// </summary>
        public static string FormatoInvalidoUrl {
            get {
                return ResourceManager.GetString("FormatoInvalidoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora(s).
        /// </summary>
        public static string Horas {
            get {
                return ResourceManager.GetString("Horas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdAplicacion.
        /// </summary>
        public static string IdAplicacion {
            get {
                return ResourceManager.GetString("IdAplicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdUsuario.
        /// </summary>
        public static string IdUsuario {
            get {
                return ResourceManager.GetString("IdUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/jpeg;base64,{0}.
        /// </summary>
        public static string ImagenJpegBase64 {
            get {
                return ResourceManager.GetString("ImagenJpegBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InnerException: .
        /// </summary>
        public static string InnerException {
            get {
                return ResourceManager.GetString("InnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje: .
        /// </summary>
        public static string Mensaje {
            get {
                return ResourceManager.GetString("Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Mes(es).
        /// </summary>
        public static string Meses {
            get {
                return ResourceManager.GetString("Meses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor incorrecto para el mes.
        /// </summary>
        public static string MesIncorrecto {
            get {
                return ResourceManager.GetString("MesIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minuto(s).
        /// </summary>
        public static string Minutos {
            get {
                return ResourceManager.GetString("Minutos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null.
        /// </summary>
        public static string Nulo {
            get {
                return ResourceManager.GetString("Nulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParametroDuracionSesion.
        /// </summary>
        public static string ParametroDuracionSesion {
            get {
                return ResourceManager.GetString("ParametroDuracionSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parámetro {0} no se encuentra configurado.
        /// </summary>
        public static string ParametroNoConfiguradoCorrectamente {
            get {
                return ResourceManager.GetString("ParametroNoConfiguradoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propiedad {0} no existe..
        /// </summary>
        public static string PropiedadDesconocida {
            get {
                return ResourceManager.GetString("PropiedadDesconocida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es-CO.
        /// </summary>
        public static string RegionColombia {
            get {
                return ResourceManager.GetString("RegionColombia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semana(s).
        /// </summary>
        public static string Semanas {
            get {
                return ResourceManager.GetString("Semanas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo caracteres alfanuméricos.
        /// </summary>
        public static string SoloCaracteresAlfanumericos {
            get {
                return ResourceManager.GetString("SoloCaracteresAlfanumericos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StackTrace: .
        /// </summary>
        public static string StackTrace {
            get {
                return ResourceManager.GetString("StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentencia switch no controlada.
        /// </summary>
        public static string SwitchNoControlado {
            get {
                return ResourceManager.GetString("SwitchNoControlado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiempoEsperaConexion.
        /// </summary>
        public static string TiempoEsperaConexion {
            get {
                return ResourceManager.GetString("TiempoEsperaConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UrlDatabaseRedis.
        /// </summary>
        public static string UrlDatabaseRedis {
            get {
                return ResourceManager.GetString("UrlDatabaseRedis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UrlServicioExcepciones.
        /// </summary>
        public static string UrlServicioExcepciones {
            get {
                return ResourceManager.GetString("UrlServicioExcepciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UrlServicioLog.
        /// </summary>
        public static string UrlServicioLog {
            get {
                return ResourceManager.GetString("UrlServicioLog", resourceCulture);
            }
        }
    }
}
