// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Proyecto.Datos.Contexto.Repositorio
{
    public partial class Padres
    {
        public Padres()
        {
            HijosIdentificacionMadreNavigation = new HashSet<Hijos>();
            HijosIdentificacionPadreNavigation = new HashSet<Hijos>();
        }

        public int Identificacion { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public DateTime FechaNacimiento { get; set; }
        public string Genero { get; set; }
        public string TipoEmpleo { get; set; }
        public int? ExperienciaLaboral { get; set; }
        public string Observaciones { get; set; }

        public virtual ICollection<Hijos> HijosIdentificacionMadreNavigation { get; set; }
        public virtual ICollection<Hijos> HijosIdentificacionPadreNavigation { get; set; }
    }
}